version: '3'
services:
  weather:
    build:
      dockerfile: ./controllers/WeatherAPIContainer/Dockerfile
    ports:
      - "5226:5226"

  detection:
    build:
      dockerfile: ./controllers/DetectionAPIContainer/Dockerfile
    ports:
      - "5227:5227"
  
  mosquitto:
        image: eclipse-mosquitto:latest
        container_name: mosquitto_broker_v2
        ports:
            - 1883:1883
            - 9001:9001
        volumes:
            - ./mosquitto/config:/mosquitto/config
            - ./mosquitto/data:/mosquitto/data
            - ./mosquitto/log:/mosquitto/log
        networks:
            - backend

networks:
    backend:
        name: trafficLight
        driver: bridge
